[google_service_account]
type = "service_account"
project_id = "verification-asensia"
private_key_id = "d0bf598dc7ef775cb0533463b66f59d2dfbb708f"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDZabgWJ3CMDRyc
kyeFcZAxfvI5Fl8RfIL/xzr12cwUJWrrNeSrIepR9MXhaRudrci1FGC1Fh22IzvO
x7KKVroQ6ZqjixN6H4nFNCqYhf4YEA2VT681AaZxUwdCq1+rIvcqBRLoKXYm+tvV
hJk6CJaC9sEna0Xqr8IwxVjjwydm/8GLMy5eHS4k0DnocbKXLdqqk5aXnQUTFSMU
qSFWShEAn4yjNk8+n5n9IbrTOpq4NqBrqSxliP8MZ5ecWvkfk/nPoDToSWDvwF4e
PF7XdfWc0RmF3e7mXVXDMXgmseUfLus2Np75RHWOSvngwaXi4WZhZh0MS31dIxkt
EdDRx1EjAgMBAAECggEAP8wM77tNBFvInI112GuVk2Cb9XKCHSB7VFEDFSd/Ah5k
vHaJDkqadsgr1NRB/UgEkFZVdm3x9ANsxmXFF2ERomraLMlfwsNEazC+mxkekbMM
OVczo4tDaxehFsgw/4f4HUV14dhgyllsbsBFMklY2T9NOKL61j4S7rrKNbOLeWZi
qwaGbq/E6tPCQnrWZHIU+l2whq3kghZrt4TStg0l4l0ZxYomMb9V5ulT2aGbAMwV
5vNHrTMFksQZY78sEFFPAyJg6MKaTxaLJ1gzsBS3ouUAAbT0y6zOp3SfX9TK2D4w
i9UGMrznLd0jnPtXTq4125naH8i2V9v7adWww5UO6QKBgQD3ExtCn2YyVzC8Hwze
t2JgpiK/m4+4tySp93xKCpMyUdVegeotDKFKWgYLaIG+NLFC3wheQSKXb7ol59Lt
iMwd6rLsPHOouWDmpi7E8UL8PJP/xDp4h/lYnse6jSQeTiBHXZecb/ghbFfGpjjb
bcTv/Ee022aMpWQHO8cLbyRBBwKBgQDhRE7MrB2OfeOvzzW3/tTsIkAbSGBf/o7H
tTc/b5rc01uLL0M32uMRAGvMjprSSO8y1MahD9m91ew76gLL2Gqa6cs34hZLXZdw
ky2MlWd3augDPJZRIIkmr1u9JCQjX5YrsXaiezMXKuDFKiy46YQuYWUz+TaKSfIr
rUD9/zaUBQKBgGbeR51HbG9NKfdJHjykMYt34EPSatZHOjah2deh64Mp2yJMCMnU
1lp0fMvHKS2eFqd24K8Ng291jxU1HfbT29gg3XnJ+YWoGRYu3o4UvQTz29LDSmzg
gApLoXCkTwNnF71e1D7Hx5Fy4GDO2CFT5IjeiqRcLKgmPC1e0BKMpZWFAoGALPu1
/JsWH+E1uWLYaFCj9i90u739OM4ddvXR/YHs29H9AtNCSgIUu81ouWV0ty9HTNA+
heUjZwwz61b0jf4+c4biRNuJ9izPU/Sf8OXYznjzscnEfpjPqoD0AdYYvVOWKk16
0kFl12eBkP22BorjEVvzmKhYYs8XY+9p/g6buH0CgYEA6Y/e+1bVOder0leNK9yf
QwQaUQcmQmXIROvWZqHuScdearIFEdNWdHoCi9vGr1tpCei3G8CiqqX/GD3Vd/q3
KJQonO8+WTexXLdIY9Zcl+ZP8VRI3/nesRLQ/1qj/hQ0kW2mR+u5SBUvA7okufIL
rRZqpJw8GRTXTY59+yYh0K8=
-----END PRIVATE KEY-----\n"""
client_email = "streamlit-sheet-bot@verification-asensia.iam.gserviceaccount.com"
client_id = "108385019624172122507"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-sheet-bot%40verification-asensia.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
